name: Comment to Commit using Aider

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write
  
jobs:
  generate:
    if: ${{ contains(github.event.comment.body, '@aider') }}
    uses: oscoreio/ai-workflows/.github/workflows/comment-to-commit-using-aider.yml@main
    with:
      comment-id: ${{ github.event.comment.id }}
      pr-url: ${{ github.event.issue.pull_request.url || github.event.pull_request.url }}
      is-review: ${{ github.event_name == 'pull_request_review_comment' }}
      test-command: "dotnet build"
    secrets:
      openrouter-api-key: ${{ secrets.OPENROUTER_API_KEY_FOR_PRS }}
      openai-api-key: ${{ secrets.OPENAI_API_KEY_FOR_PRS }}
      anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY_FOR_PRS }}
      groq-api-key: ${{ secrets.GROQ_API_KEY_FOR_PRS }}
      gemini-api-key: ${{ secrets.GEMINI_API_KEY_FOR_PRS }}
      cohere-api-key: ${{ secrets.COHERE_API_KEY_FOR_PRS }}
      deepseek-api-key: ${{ secrets.DEEPSEEK_API_KEY_FOR_PRS }}