name: Issue to PR using Aider
on:
  issues:
    types: [labeled]

jobs:
  generate:
    uses: oscoreio/ai-workflows/.github/workflows/issue-to-pr-using-aider.yml@main
    if: startsWith(github.event.label.name, 'aider')
    with:
      issue-number: ${{ github.event.issue.number }}
      default-branch: ${{ github.event.repository.default_branch }}
      test-command: "dotnet build"
    secrets:
      openrouter-api-key: ${{ secrets.OPENROUTER_API_KEY_FOR_PRS }}
      openai-api-key: ${{ secrets.OPENAI_API_KEY_FOR_PRS }}
      anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY_FOR_PRS }}
      groq-api-key: ${{ secrets.GROQ_API_KEY_FOR_PRS }}
      gemini-api-key: ${{ secrets.GEMINI_API_KEY_FOR_PRS }}
      cohere-api-key: ${{ secrets.COHERE_API_KEY_FOR_PRS }}
      deepseek-api-key: ${{ secrets.DEEPSEEK_API_KEY_FOR_PRS }}
